// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using ModLinker;
using System.Collections.Generic;
using System;

namespace ModLinker.Tables
{
   public sealed partial class DirectoryTable : TableBase<Directory>, ITableUniqueValidate
   {
        public Func<Directory, string> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<Directory, string> primaryIndexSelector;


        public DirectoryTable(Directory[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => x.Path;
            OnAfterConstruct();
        }

        partial void OnAfterConstruct();


        public Directory FindByPath(string key)
        {
            return FindUniqueCore(data, primaryIndexSelector, System.StringComparer.Ordinal, key, false);
        }
        
        public bool TryFindByPath(string key, out Directory result)
        {
            return TryFindUniqueCore(data, primaryIndexSelector, System.StringComparer.Ordinal, key, out result);
        }

        public Directory FindClosestByPath(string key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.StringComparer.Ordinal, key, selectLower);
        }

        public RangeView<Directory> FindRangeByPath(string min, string max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.StringComparer.Ordinal, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
            ValidateUniqueCore(data, primaryIndexSelector, "Path", resultSet);       
        }

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(Directory), typeof(DirectoryTable), "directories",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(Directory).GetProperty("Path")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(Directory).GetProperty("Path"),
                    }, true, true, System.StringComparer.Ordinal),
                });
        }

    }
}